name: executorch_vision
description: "SDK amigavel para inferÃªncia de modelos de visÃ£o computacional com o Executorch Flutter."
version: 1.0.0
homepage: https://github.com/mauriciobenjamin700/executorch_vision
repository: https://github.com/mauriciobenjamin700/executorch_vision
issue_tracker: https://github.com/mauriciobenjamin700/executorch_vision/issues
documentation: https://github.com/mauriciobenjamin700/executorch_vision/wiki

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.1
  camera: ^0.11.3
  executorch_flutter: ^0.3.0
  path_provider: ^2.1.5
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
